services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: do_indeksa
      POSTGRES_PASSWORD: do_indeksa
      POSTGRES_DB: do_indeksa
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
